url: "https://pgu.dev"

markdown: kramdown
remote_theme: thelehhman/texture
plugins:
  - jekyll-feed

texture:
  title: Paulius Gudonis
  tagline: Software developer
  style: [black]
  date_format: "%b %-d, %Y"

  social_links:
    twitter: nakkht
    github:  nakkht
    linkedIn: in/pauliusgudonis