baseurl: ""
url: "https://pgu.dev"

theme_settings :
  title : Paulius Gudonis

  profile :
    image : assets/img/me.jpg
    username : Paulius Gudonis
    description: Software Developer, Architect

  icons :
    email: paulius.gudonis.92@gmail.com
    linkedin: https://linkedin.com/in/pauliusgudonis
    github: nakkht
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: nakkht
    youtube:
    facebook:
    instagram:

paginate: 5
paginate_path: "blog/page:num"

sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true