baseurl: ""
url: "https://pgu.dev"

theme_settings:
  title: Paulius Gudonis
  favicon : assets/favicon.ico

  profile:
    image: assets/img/me.jpg
    username: Paulius Gudonis
    description: Software Developer, Architect

    skills: 
        - skill: Android / iOS, Java, Kotlin, Swift, Objective-C, Python, Go, Rust, C#, Git, ASP.NET Core, Docker
        - skill: MVP, MVVM-C, MVC, Git flow, Unit testing, Continuous Integration / Delivery

    experience:

        - start: 2019-06
          end: Present
          experience: Saphe A/S, App Developer

        - start: 2018-10
          end: Present
          experience: neqsoft, Owner/Freelancer

        - start: 2016-01
          end: 2019-05
          experience: Medei ApS, Lead Software Developer

        - start: 2014-11
          end: 2015-10
          experience: Internet Chess Club, Software Developer
     
  icons:
    email: pg@neqsoft.com
    linkedin: https://linkedin.com/in/pauliusgudonis
    github: nakkht
    twitter: nakkht

sass:
  sass_dir: _sass
  style: :compressed

bootstrap:
  assets: true